version: '3.7'

services:
  stress:
    image: mohsenmottaghi/container-stress
    lables:
      co.mohsen.docker.container: container-stress 
      co.mohsen.docker.author: "Mohsen Mottaghi"
      co.mohsen.docker.infra: stress-test-area
    command: stress --verbose --vm 1 --vm-bytes 512M
    deploy:
      replicas: 5
      # If you don`t know why you should define these elements, Don`t Change them!
      # resources:
      #   limits:
      #     cpus: '0.50'
      #     memory: 512M
      #   reservations:
      #     cpus: '0.25'
      #     memory: 200M
      restart_policy:
        condition: on-failure
        delay: 2s